#include <stdlib.h>
#include <stdio.h>
int main()
{
    char *key = "-----BEGIN OPENSSH PRIVATE KEY-----\
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\
QyNTUxOQAAACAFyIt147zzkbTwWiQjd0s6EhG25XfGhW1TKX3GYdEwCgAAAKALRN3uC0Td\
7gAAAAtzc2gtZWQyNTUxOQAAACAFyIt147zzkbTwWiQjd0s6EhG25XfGhW1TKX3GYdEwCg\
AAAEAfi/p+pYS6jydNGdizO2fZufmKBmAv2h84qmjfYo8ztgXIi3XjvPORtPBaJCN3SzoS\
Ebbld8aFbVMpfcZh0TAKAAAAFnlvdXJfZW1haWxAZXhhbXBsZS5jb20BAgMEBQYH\
-----END OPENSSH PRIVATE KEY-----";
    
    return 0;
}
