#include <stdlib.h>
#include <stdio.h>
int main()
{
    char *key = "-----BEGIN OPENSSH PRIVATE KEY----- \
MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALeb2KkOe9gFVlLS \
Dbz+O7mXcDcgFvYre1G9UOIiIrkFLk+huGhvbmRE+e71moELbDi5/COUusfhVwv4 \
4tQA6LVgbCwwm8J1TmSVgLxImKEI95ew+AM7PlxC3+2yIvNSOK16OIimOgS9gjj1 \
3EG1q5TVgXdDxwOZNUFrJKJGShSHAgMBAAECgYBa2P7j7ymx4jorMonfqH+OvfKl \
I/iYhz02XZDmwvMhTwHyHteqvPAHJuXvqZBwJ2G907CBPncIrWOvpc8+DNEXDtmj \
ls0CxmPR7NB84E1W5uyCpS8p/J3nwmsCfKThzdiMii30axLaipYfxs859i9N6iUl \
0OTnFZ3afC0EMRts+QJBAOBOQG7oQNTayCoDIMHxXwVKixa8sDNWQLUoFzPtbbEt \
oysrCVTNH4CAJxH0I/mRobCV1OsXg9jLunuQhmFu2MUCQQDRjXoR9BqRF4BnlmIm \
N+r9T0OdZiTDFPhRMxL+E23oZGmhikJ/VqrKa3fz8NNlO/+nWPm3XEgZG/IM4Spx \
XlTbAkBbwYb4F4gVyp2hGgB3db6SEolNNsi5Z2o28Px04IZDuVCLIyLBDtv5G/Nf \
k8h3mgxTiSc9ODRWJhjV3SwrhUWlAkEAjwHC/b+d5cipG4hYgQaGOsq+NQuBKRUF \
hbyaSISP7BmisNh/GxHVSoDfAr4mNh8lEFq7SHQUy/XzUPDVGzsqIwJAZN4MeTxe \
rSkmY5cn/CZGVF0KSXj7CDfMETewRyjUEmeuBZfd07PRUGUY7/kRfQnnR2jQT/ZT \
HuJhDttPyJ0wug== \
-----END OPENSSH PRIVATE KEY-----";
      return 0;
}
